maps = ["""
|x|x|x|M0|M0|M0|M0|x|x|x|
|x|x|x|_|_|_|_|x|x|x|
|x|T(1,9,5)|x|_|_|_|_|x|x|x|
|M0|_|_|_|_|_|_|_|_|M0|
|M0|_|_|_|_|_|_|_|_|M0|
|M0|_|_|_|_|_|_|_|_|M0|
|M0|_|_|_|_|_|_|_|_|M0|
|x|x|x|_|_|_|_|x|x|x|
|x|x|T(1,5,10)|_|_|_|_|x|x|x|
|x|x|x|M0|M0|M0|M0|x|x|x|
""",
"""
|_|_|_|_|_|_|_|_|_|_|_|
|_|_|_|_|_|_|_|_|_|_|_|
|_|x|x|x|x|x|x|x|x|x|_|
|_|x|_|_|_|_|_|_|_|x|_|
|_|x|_|_|_|_|_|_|_|x|x|
|_|x|_|_|_|_|_|_|_|_|T(0,8,3)|
|_|x|_|_|_|_|_|_|_|x|x|
|_|x|_|_|_|_|_|_|_|x|_|
|_|x|x|x|x|_|x|x|x|x|_|
|_|_|_|_|x|T(0,3,1)|x|_|_|_|_|
"""
]

start_pos = [1,3]

[[global_items]]
item_id = "sword"
at = 6

[[global_items]]
item_id = "aoeu"
at = 3


[player]
name = "Julian"
total_health = 30
character_type = "Zauberer"

[player.rp_properties]
at = 1
aw = 6
rs = 2

